version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: clinic-service-system-db
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
  clinic-system:
    depends_on:
      - db
    container_name: clinic-system
    image: fil1ip/clinic-system:latest
    ports:
      - "80:8080"
    environment:
      MYSQL_HOST: db
volumes:
  my-db: